- AccountAPI/src/main/java/net/skhu/mentoring/controller/GuestRestController.java
- AccountAPI/src/main/java/net/skhu/mentoring/controller/ResourceRestController.java
- AccountAPI/src/main/java/net/skhu/mentoring/domain/Account.java
- AccountAPI/src/main/java/net/skhu/mentoring/domain/Employee.java
- AccountAPI/src/main/java/net/skhu/mentoring/domain/Professor.java
- AccountAPI/src/main/java/net/skhu/mentoring/domain/Student.java
- AccountAPI/src/main/java/net/skhu/mentoring/enumeration/Gender.java
- AccountAPI/src/main/java/net/skhu/mentoring/model/EmployeeSignModel.java
- AccountAPI/src/main/java/net/skhu/mentoring/model/ProfessorSignModel.java
- AccountAPI/src/main/java/net/skhu/mentoring/model/StudentSignModel.java
- AccountAPI/src/main/java/net/skhu/mentoring/repository/AccountRepository.java
- AccountAPI/src/main/java/net/skhu/mentoring/repository/AvailableTimeRepository.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/implement_objects/GuestServiceImpl.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/implement_objects/ResourceServiceImpl.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/interfaces/GuestService.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/interfaces/ResourceService.java
ResourceController -> 회원 조사 여부를 거치지 않아도 되는 데이터 목록을 GET URL 를 이용하여 가져오는 목적으로 생성,
GuestController -> 각 학생, 교수, 직원 별 회원 가입 기능 추가.
> ResourceController, GuestController 작성

- AccountAPI/src/main/java/net/skhu/mentoring/controller/CommonRestController.java
- AccountAPI/src/main/java/net/skhu/mentoring/model/AvailableTimeModel.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/implement_objects/CommonServiceImpl.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/implement_objects/GuestServiceImpl.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/interfaces/CommonService.java
- AccountAPI/src/main/java/net/skhu/mentoring/vo/AvailableTimeVO.java
회원 정보 수정하는 기능 구현하였음.
이제 프로필 수정하는 기능에 대해서 구현하고 난 후에 내일 알바가 펑크 난 기념으로 엑셀로 저장 받는 방안에 대해서 구현할 예정.
Web Application 도 같이 새로 구현한 내용이 있으니 참고 바람.
> Create Sign Update Function

- AccountAPI/src/main/java/net/skhu/mentoring/controller/AdminRestController.java
- AccountAPI/src/main/java/net/skhu/mentoring/repository/ProfessorRepository.java
- AccountAPI/src/main/java/net/skhu/mentoring/repository/StudentRepository.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/implement_objects/AdminServiceImpl.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/interfaces/AdminService.java
- AccountAPI/src/main/java/net/skhu/mentoring/vo/EmployeeViewVO.java
- AccountAPI/src/main/java/net/skhu/mentoring/vo/ProfessorViewVO.java
- AccountAPI/src/main/java/net/skhu/mentoring/vo/StudentViewVO.java
관리자가 회원 정보 열람할 수 있는 기능을 구현하였음.
그리고 그 페이지 내부에서 학과장, 학생회장 설정하는 기능도 부여하였음.
참고로 학생 회장 설정은 교수, 직원만 가능하도록 설정함.
> Create Account View Function

- AccountAPI/src/main/java/net/skhu/mentoring/controller/AdminRestController.java
- AccountAPI/src/main/java/net/skhu/mentoring/repository/DepartmentRepository.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/implement_objects/ExcelUploadServiceImpl.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/interfaces/ExcelUploadService.java
엑셀 업로드 관련 Controller 단위까지 구현 완료.
이전에 Excel 를 이용한 업로드 기능을 이용한 함수와 유사함. Apache POI 이용.
React Component 측에서 Form 형식 다운로드는 완료하였으나, 업로드는 내일부터 적용할 예정.
> Excel Uploading Function Add

- AccountAPI/src/main/java/net/skhu/mentoring/controller/AdminRestController.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/implement_objects/ExcelUploadServiceImpl.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/interfaces/AdminService.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/interfaces/ExcelUploadService.java
엑셀 업로드 기능 일부 데이터베이스 충돌 문제에 대하여 처리하였음.
> Update AccountAPI - Excel Uploading Function

- MentoAPI/src/main/java/net/skhu/mentoring/domain/ClassPhoto.java
- MentoAPI/src/main/java/net/skhu/mentoring/domain/Menti.java
- MentoAPI/src/main/java/net/skhu/mentoring/domain/Report.java
- MentoAPI/src/main/java/net/skhu/mentoring/domain/Schedule.java
- MentoAPI/src/main/java/net/skhu/mentoring/domain/Semester.java
- MentoAPI/src/main/java/net/skhu/mentoring/domain/StickyNote.java
- MentoAPI/src/main/java/net/skhu/mentoring/domain/StickyPhoto.java
- MentoAPI/src/main/java/net/skhu/mentoring/domain/Subject.java
- MentoAPI/src/main/java/net/skhu/mentoring/domain/Team.java
- MentoAPI/src/main/java/net/skhu/mentoring/domain/TeamAdvertiseFile.java
- MentoAPI/src/main/java/net/skhu/mentoring/enumeration/ResultStatus.java
도메인 객체 클래스 생성 완료. Repository 는 JpaRepository 이용 했던 걸로 그대로 적용하면 됨.
> Create MentoAPI - Add Domain Object Class

- AccountAPI/src/main/java/net/skhu/mentoring/controller/CommonRestController.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/implement_objects/CommonServiceImpl.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/interfaces/CommonService.java
- NoticeAPI/README.md
> Update AccountAPI - Profile Saving, Releasing Function

- NoticeAPI/src/main/java/net/skhu/mentoring/model/CalendarModel.java
- NoticeAPI/src/main/java/net/skhu/mentoring/model/DetailModel.java
- NoticeAPI/src/main/java/net/skhu/mentoring/model/IntroModel.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/AlertRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/AlertTypeRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/CalendarRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/CommentRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/DetailRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/FileRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/ImageRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/IntroRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/PostRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/SurveyRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/TypeRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/CalendarRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/IntroduceRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/CalendarServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/IntroduceServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/interfaces/CalendarService.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/interfaces/IntroduceService.java
- NoticeAPI/src/main/java/net/skhu/mentoring/vo/CalendarVO.java
- NoticeAPI/src/main/java/net/skhu/mentoring/vo/DetailVO.java
- NoticeAPI/src/main/java/net/skhu/mentoring/vo/IntroVO.java
- NoticeAPI/src/main/java/net/skhu/mentoring/vo/IntroduceVO.java
소개문, 일정 관련 CRUD 작업을 진행하기 위한 REST API 구성 완료.
이후로 알립니다 기능을 위한 REST API 구축 예정.
> Notice API - Create Introduce, Calendar REST API

- NoticeAPI/src/main/java/net/skhu/mentoring/domain/File.java
- NoticeAPI/src/main/java/net/skhu/mentoring/domain/Image.java
- NoticeAPI/src/main/java/net/skhu/mentoring/model/CommentModel.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/CommentRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/FileRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/ImageRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/PostRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/CalendarRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/CommentRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/FileRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/IntroduceRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/NoticeRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/NoticeCommentServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/NoticeFileServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/NoticeIntegrateServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/interfaces/NoticeCommentService.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/interfaces/NoticeFileService.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/interfaces/NoticeIntegrateService.java
- NoticeAPI/src/main/java/net/skhu/mentoring/vo/NoticeCommentVO.java
- NoticeAPI/src/main/java/net/skhu/mentoring/vo/NoticeFileBriefVO.java
Web Application 에서 알립니다(공지사항, 자유게시판 등) 기능에 대해 REST API 구축 완료함.
그리고 NoticeAPI 측의 URI 를 원칙적으로 축약하는 작업 때문에 늦어졌음.
내일부터 설문조사 기능과 알림 기능, MentoAPI Service 단위까지 구현할 수 있도록 빠른 작업이 진행될 것으로 판단됨.
또한 AccountAPI 측의 URI이 변경될 수 있으니 이 점 참고 바람.
> Create Notice Function API Structure

- NoticeAPI/src/main/java/net/skhu/mentoring/enumeration/SurveyType.java
- NoticeAPI/src/main/java/net/skhu/mentoring/model/SurveyModel.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/SurveyRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/SurveyRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/NoticeIntegrateServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/SurveyServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/interfaces/SurveyService.java
설문조사 기능을 추가한 REST API 생성 완료.
Alert (안내) 사항은 Web Socket 관련 설정이 필요하기 때문에 우선 Mento API 측 부터 완성하고 진행할 예정.
> Create Survey Function

- MentoAPI/src/main/java/net/skhu/mentoring/domain/Schedule.java
- MentoAPI/src/main/java/net/skhu/mentoring/model/MentiApplicationModel.java
- MentoAPI/src/main/java/net/skhu/mentoring/model/MentoAppicationModel.java
- MentoAPI/src/main/java/net/skhu/mentoring/model/PanelPagination.java
- MentoAPI/src/main/java/net/skhu/mentoring/model/ReportModel.java
- MentoAPI/src/main/java/net/skhu/mentoring/model/ScheduleModel.java
- MentoAPI/src/main/java/net/skhu/mentoring/model/SemesterModel.java
- MentoAPI/src/main/java/net/skhu/mentoring/model/SubjectModel.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/ClassPhotoRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/MentiRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/ReportRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/ScheduleRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/SemesterRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/StickyNoteRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/StickyPhotoRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/SubjectRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/TeamAdvertiseRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/TeamRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/rest_controller/MentoringRestController.java
- MentoAPI/src/main/java/net/skhu/mentoring/rest_controller/ReportRestController.java
- MentoAPI/src/main/java/net/skhu/mentoring/rest_controller/ScheduleRestController.java
- MentoAPI/src/main/java/net/skhu/mentoring/rest_controller/SemesterRestController.java
- MentoAPI/src/main/java/net/skhu/mentoring/rest_controller/SubjectRestController.java
MentoAPI 구축 작업을 시작하였음.
오늘은 REST API 의 URI 를 올렸음.
> MentoAPI Structure

- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/NoticeIntegrateServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/vo/NoticePostBriefVO.java
내가 봤을떄 NoticePostBriefVo에서 api 바꾸는 거 같은데 바꿨는데도 안 바뀌네
확인 한번 해주라
> notice 시간 보여주기

- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/NoticeRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/NoticeIntegrateServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/vo/NoticeListIntegrateVO.java
- NoticeAPI/src/main/java/net/skhu/mentoring/vo/NoticePostBriefVO.java
- README.md
공지사항 글을 검색할 때 페이징네이션 객체까지 반환함.
그리고 README.md 글 일부 추가하였음.
> Update MentoAPI - Add NoticeListIntegrateVO Object

- NoticeAPI/src/main/java/net/skhu/mentoring/vo/CalendarVO.java
Calendar 정보에서 id 와 작성자를 추가하였음.
> Update NoticeAPI - CalendarVO.java

- MentoAPI/src/main/java/net/skhu/mentoring/domain/Team.java
- MentoAPI/src/main/java/net/skhu/mentoring/model/MentiApplicationModel.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/MentiRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/SemesterRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/TeamAdvertiseRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/TeamRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/rest_controller/MentoringRestController.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/implement_objects/MentiServiceImpl.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/implement_objects/TeamServiceImpl.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/interfaces/MentiService.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/interfaces/TeamService.java
- MentoAPI/src/main/java/net/skhu/mentoring/vo/MentiAppVO.java
- MentoAPI/src/main/java/net/skhu/mentoring/vo/MentoVO.java
- MentoAPI/src/main/java/net/skhu/mentoring/vo/PersonVO.java
멘토링 신청(멘토 신청, 멘티 신청) 작업을 위한 REST API 구축 완료.
Service 클래스 까지 작성 완료하여 실제로 연동해뒀음.
> Create MentoAPI - MentoringRestController.java

- AccountAPI/src/main/java/net/skhu/mentoring/controller/GuestRestController.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/implement_objects/GuestServiceImpl.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/interfaces/GuestService.java
- AccountAPI/src/main/java/net/skhu/mentoring/util/Mail.java
- AccountAPI/src/test/java/net/skhu/mentoring/main/PasswordTest.java
> 패스워드 인증번호 발송 성공

- NoticeAPI/src/main/java/net/skhu/mentoring/model/PostModel.java
- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/FileRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/NoticeRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/NoticeFileServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/NoticeIntegrateServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/interfaces/NoticeFileService.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/interfaces/NoticeIntegrateService.java
파일 다중 업데이트가 안 되어 이로 교체하였음.
그리고 게시글 추가, 수정 작업을 위해 게시글 모델을 반환하는 기능 추가함.
> Update NoticeAPI - About MultiPart Array

- MentoAPI/src/main/java/net/skhu/mentoring/domain/Schedule.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/MentiRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/repository/TeamRepository.java
- MentoAPI/src/main/java/net/skhu/mentoring/rest_controller/MentoringRestController.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/implement_objects/MentiServiceImpl.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/implement_objects/TeamServiceImpl.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/interfaces/MentiService.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/interfaces/TeamService.java
- MentoAPI/src/main/java/net/skhu/mentoring/vo/CareerBriefVO.java
멘토와 멘티 경력 조회를 위한 기능 추가 탑재, 멘토링 신청 내역 수정 기능에서 파일 유무에 따른 설정 탑재
> Update MentoAPI - Add Mento, Menti Careers & Updating

- MentoAPI/src/main/java/net/skhu/mentoring/model/ReportModel.java
- MentoAPI/src/main/java/net/skhu/mentoring/rest_controller/ReportRestController.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/implement_objects/ReportExcelServiceImpl.java
- MentoAPI/src/main/java/net/skhu/mentoring/vo/MentoringTokenVO.java
- MentoAPI/src/main/java/net/skhu/mentoring/vo/ReportBriefVO.java
- NoticeAPI/src/main/java/net/skhu/mentoring/repository/CalendarRepository.java
보고서 다운로드에서 엑셀 너비 맞추는 작업과 보고서 작성 중 멘토와의 유효성 확인하는 기능 추가.
> Update MentoAPI - Report Function Update

- NoticeAPI/src/main/java/net/skhu/mentoring/repository/ImageRepository.java
- NoticeAPI/src/main/java/net/skhu/mentoring/rest_controller/FileRestController.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/integrate_objects/NoticeFileServiceImpl.java
- NoticeAPI/src/main/java/net/skhu/mentoring/service/interfaces/NoticeFileService.java
> Update NoticeAPI - Update About FileRestController.java

- AccountAPI/src/main/java/net/skhu/mentoring/config/SecurityConfig.java
- AccountAPI/src/main/java/net/skhu/mentoring/controller/ResourceRestController.java
- AccountAPI/src/main/java/net/skhu/mentoring/service/implement_objects/AdminServiceImpl.java
- MentoAPI/src/main/java/net/skhu/mentoring/rest_controller/MentoringRestController.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/implement_objects/SubjectServiceImpl.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/implement_objects/TeamServiceImpl.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/interfaces/SubjectService.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/interfaces/TeamService.java
- MentoAPI/src/main/java/net/skhu/mentoring/vo/AdminAppVO.java
> Update Mento/AccountAPI - Add Mentoring Opening Function

- MentoAPI/src/main/java/net/skhu/mentoring/model/ConfirmModel.java
- MentoAPI/src/main/java/net/skhu/mentoring/rest_controller/MentoringRestController.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/implement_objects/ReportExcelServiceImpl.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/implement_objects/ScheduleServiceImpl.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/implement_objects/TeamServiceImpl.java
- MentoAPI/src/main/java/net/skhu/mentoring/service/interfaces/TeamService.java
보고서 기능 확인에 대하여 첨가하기 위하여 필요 없는 기능을 일부 없애거나 추가 하였음.
> Update MentoAPI - Small Updating To Implement Report Checking
